#!/usr/bin/env bash
# The script transfers a file from client to server
# accepts 4 parameters

if [ "$#" -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
	exit 1"
fi

#Assigning parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Disable strict host key checking for scp
# scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
SCP_COMMAND="scp -o StrictHostKeyChecking=no -i $PATH_TO_SSH_KEY $PATH_TO_FILE $USERNAME@IP:~"

#Transfer the file using scp
$SCP_COMMAND
