#!/usr/bin/env bash
# Installing nginx on default port using apt-get

sudo apt-get update -y
sudo apt-get install nginx -y

FILE_PATH="/var/www/html/index.html"
sudo bash -c "echo 'Hello World!' > $FILE_PATH"

sudo service nginx restart
