#!/usr/bin/env bash
# Installing nginx on default port using apt-get

# Installing nginx on default port 80
sudo apt-get update -y
sudo apt-get install nginx -y

# Creating an index file that displays 'Hello World!'
FILE_PATH="/var/www/html/index.html"
sudo bash -c "echo 'Hello World!' > $FILE_PATH"

# Restarting the nginx server without using systemctl
sudo service nginx restart
