#!/usr/bin/env bash
# Installing nginx on default port using apt-get

# Installation of nginx using the get
sudo apt-get update -y
sudo apt-get install nginx -y

# Set file paths
NGINX_CONF="/etc/nginx/sites-available/default"


# Setting write authorization procedure
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www


# Creating an index file that displays 'Hello World!'
FILE_PATH="/var/www/html/index.html"
sudo bash -c "echo 'Hello World!' > $FILE_PATH"


# Setting up / redirect_me to a youtube video
sed -i '24i\
        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' "$NGINX_CONF"


# Restarting nginx
sudo service nginx restart
