#!/usr/bin/env bash
# Installing nginx on default port using apt-get

# Installation of nginx using the get
sudo apt-get update -y
sudo apt-get install nginx -y

# Set file paths
ERROR_404_FILE="/var/www/html/error_404.html"
NGINX_CONF="/etc/nginx/sites-available/default"

# Setting up a custom 404 page
echo "Ceci n'est pas une page" >> "$ERROR_404_FILE"
# sudo sed -i '/server_name _;/a\       error_page 404 /error_404.html;' $NGINX_CONF

# Setting up / redirect to a youtube video
sed -i '/server_name _;/r /dev/stdin' "$NGINX_CONF" <<EOF
    error_page 404 /error_404.html;
    location /error_404.html {
        root /var/www/html;
        internal;
    }
    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
EOF

# Restarting nginx
sudo service nginx restart
