#!/usr/bin/env bash
#

function sig_handler() {
	case $1 in
		SIGTERM)
			echo "I hate the kill command"
			;;
		SIGINT)
			echo "Y U no love me?!"
			;;
		SIGQUIT)
			cleanup_and_exit
			;;
	esac
}

function cleanup_and_exit() {
	rm -f /var/run/myscript.pid
	exit 0
}


trap 'sig_handler SIGTERM' SIGTERM
trap 'sig_handler SIGINT' SIGINT
trap 'sig_handler SIGQUIT' SIGQUIT


echo $$ > /var/run/myscript.pid


while true; do
	echo "To infinity and beyond"
	sleep 2
done
