#!/usr/bin/env bash
#

function sig_handler() {
	case $1 in
		SIGTERM)
			echo "I hate the kill command";
			rm -rf /var/run/_akinbo.pid;
			exit
			;;
		SIGINT)
			echo "Y U no love me?!"
			;;
		SIGQUIT)
			rm -rf /var/run/_seun.pid; exit
			;;
	esac
}


trap 'sig_handler SIGTERM' SIGTERM
trap 'sig_handler SIGINT' SIGINT
trap 'sig_handler SIGQUIT' SIGQUIT


echo $$ > /var/run/myscript.pid


while true; do
	echo "To infinity and beyond"
	sleep 2
done
