#!/usr/bin/env bash
# The script:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT

function sig_handler() {
	case $1 in
		SIGTERM)
			echo "I hate the kill command";
			rm -rf /var/run/myscript.pid;
			exit
			;;
		SIGINT)
			echo "Y U no love me?!"
			;;
		SIGQUIT)
			rm -rf /var/run/myscript.pid; exit
			;;
	esac
}


trap 'sig_handler SIGTERM' SIGTERM
trap 'sig_handler SIGINT' SIGINT
trap 'sig_handler SIGQUIT' SIGQUIT


echo $$ > /var/run/myscript.pid


while true; do
	echo "To infinity and beyond"
	sleep 2
done
