#!/usr/bin/env bash
# Bash script to group visitors by IP and
# HTTP status code from Apache log using awk
file="apache-access.log"
awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' $file | sort -nr
