#!/usr/bin/env bash
# The script displays all active IPv4 IPs using ifconfig
# and filter out loopback addresses

ips=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | cut -b 6-)
echo "$ips"
