#!/usr/bin/env bash
# The script creates a 4096 bits RSA key pair saved in
# school and school.pub in the .ssh, with
# the betty as the passphrase

KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

if [ -f ~/.ssh/$KEY_NAME]; then
	echo "Key '$KEY_NAME' already exists. Aborting."
	exit 1
fi

ssh-keygen -b $BITS -t rsa -f ~/.ssh/$KEY_NAME -N "$PASSPHRASE"
